/******************************
脚本名称：成都地铁签到
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：成都地铁App每日签到
使用说明：添加到重写和定时任务，每天9:10自动签到
*******************************/

[rewrite_local]
^https://app\.cdmetro\.chengdurail\.cn/platform/users/user/sign-in-integral(-day)?(\?.*)?$ url script-request-header https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/cd-rail/cd-rail.js

[task_local]
10 9 * * * https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/cd-rail/cd-rail.js, tag=成都地铁签到, enabled=true

[MITM]
hostname = app.cdmetro.chengdurail.cn
