/******************************
脚本名称：V2EX论坛签到
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：V2EX论坛每日签到领取铜币
使用说明：添加到重写和定时任务，每天9:10自动签到
*******************************/

[rewrite_local]
^https://www\.v2ex\.com/(mission|member).* url script-request-header https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/v2ex/v2ex.js

[task_local]
10 9 * * * https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/v2ex/v2ex.js, tag=V2EX 每日签到, enabled=true, img-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/V2ex.png

[MITM]
hostname = %APPEND% www.v2ex.com
